Pecos 1D3D interactivity
rcsb/rcsb-pecos-app pull request #2
Opened 2023-04-14 16:59 UTC by bioinsilico

- Using saguaro 1D3D module in pecos
- Adding logic for displaying MSA
- react 18
- update + audit
- webpack-dev-server

2023-04-18 00:03 UTC, valasatava requested changes
Thank you, Joan! Please, see my comments below.

My main concern is adding multiple saguaro and molstar dependencies:
```
    "@rcsb/rcsb-saguaro-3d": "^3.0.0-data-provider.29",
    "@rcsb/rcsb-saguaro-app": "^5.0.0-data-provider.20",
    "@rcsb/rcsb-molstar": "^2.5.3",
    "molstar": "^3.31.4",

``` 

It can result in multiple versions of the same library being loaded into the application causing issues (plus a disadvantage of increased bundle size). Perhaps, re-exporting things that are needed upstream or factoring them out into smaller reusable libs could help. For example, things that are used from molstar library can be re-exported via rcsb-molstar. Dependency on both rcsb-saguaro-3d and rcsb-saguaro-app should be also avoided.

P.s. there is a conflict with master branch.

2023-04-18 00:03 UTC, valasatava commented on package.json
> +    "webpack-dev-server": "^4.11.1"
with this there are now two ways to run a development server and the old way is broken, can you please refactor it to either fix and keep the old way or remove it completely

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/ExternalAlignmentProvider.ts
> +    async getTargets(): Promise<string[]> {
could be made simple by using `await`

```
const d = await this.data();
return d.target_alignment?.map(ta=>ta?.target_id ?? 'NA') ?? [];
```

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/ExternalAlignmentProvider.ts
> +    async getAlignment(): Promise<AlignmentResponse> {
maybe just `return this.data();`

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/ExternalAlignmentProvider.ts
> +        return new Promise((resolve)=>{
simpler with `await`

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/ExternalAlignmentProvider.ts
> +        return new Promise((resolve)=>{
`await` to the rescue

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/ExternalAlignmentProvider.ts
> +            this.data().then((d)=>resolve(d));
could be made simple by using `await`

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/AlignmentTrackFactory.ts
> +import { RcsbFvDisplayTypes, RcsbFvRowConfigInterface } from '@rcsb/rcsb-saguaro';
this is missing with a fresh install

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/AlignmentReference.ts
> +            if (typeof v === 'undefined')
v === undefined should be OK

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/AlignmentTrajectoryPresetProvider.ts
> +            let assemblyId = 1;
you can find the assembly with a specific entity using

```
ModelSymmetry.Provider.get(model.data!)?.assemblies[0].operatorGroups[0].asymIds
```

and

```
model.data?.properties.structAsymMap.get('A')?.entity_id
```

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/AlignmentRepresentationPresetProvider.ts
> +                        uniqid(`${entryId}${TagDelimiter.entity}${alignedEntityId}${TagDelimiter.instance}${alignedAsymId}${TagDelimiter.entity}${alignedOperators.join(',')}`),
could use `structureCell.transform.ref` as a prefix to get a unique id instead of using the `uniqid` library

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/AlignmentRepresentationPresetProvider.ts
> +import { TagDelimiter } from '@rcsb/rcsb-saguaro-app';
would be better to have it in a more general library (api tools?)

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/AlignmentTrajectoryPresetProvider.ts
> +                colorConfig.setAlignmentIdToModel(structure.data?.model.id, alignmentId);
instead of creating a TrajectoryHierarchyPresetProvider and color theme for each structure you can add data to structure.data.inheritedPropertyData like in https://github.com/molstar/rcsb-molstar/blob/b8665e2731dbdd3b04a37bfa495e824a7db92ea2/src/viewer/helpers/preset.ts#L189 and access that in a generic color theme

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/AlignmentRepresentationPresetProvider.ts
> +                        await matrixAlign(plugin, structureRef, params.transform?.[0].transform);
would be more logical to have this in the TrajectoryHierarchyPresetProvider which creates structures

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/AlignmentRepresentationPresetProvider.ts
> +
I find it a bit hard to follow, for future readers it could be helpful to add some comments saying what component you are creating next. Also some helper functions to create the component labels/keys could be useful for readability.

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/FlexibleAlignmentTrajectoryPresetProvider.ts
> +export function getTrajectoryPresetProvider(alignmentId: string, colorConfig: ColorConfig) {
the only difference to AlignmentTrajectoryPresetProvider seems to be the transform handling, I think it makes sence to merge the two files.

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/Coloring.ts
> +            const closeResidues = colorConfig.getCloseResidues(modelId);
if the hierarchy preset would add ctx.structure.inheritedPropertyData.closeResidueConfig (or some other name) it could be used instead of creating many color themes

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/FlexibleAlignmentBuiltIn.ts
> +                        throw new Error('');
should have an error message?

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/FlexibleAlignmentBuiltIn.ts
> +            throw new Error('');
should have an error message

2023-04-18 00:03 UTC, valasatava commented on src/ui/plugin.tsx
> +                                group: GroupReference.MatchingUniprotAccession,
what's the relevance of it in the context of pairwise alignment tool?

2023-04-18 00:03 UTC, valasatava commented on src/ui/plugin.tsx
> +                                alignment: (ac, ta)=>{
unused parameters. To improve readability and the intention of your code can prefix with underscore to inform that even though this callback method takes two parameters, they are not needed

2023-04-18 00:03 UTC, valasatava commented on src/index.html
> +  <title>RCSB PDB PFV UniProt Group</title>
looks like a copy pase artifact

2023-04-18 00:03 UTC, valasatava commented on src/ui/plugin.tsx
>      useObservable<Status>(props.ctx.state.events.status, setState);
was there a reasone to use `useEffect` instead of conditional rendering?

2023-04-18 00:03 UTC, valasatava commented on src/ui/plugin.tsx
> +    useEffect(()=>{
I think, specifying dependency is the "react" way to control when it runs

2023-04-18 00:03 UTC, valasatava commented on src/ui/plugin.tsx
> +                            // TODO Very ugly but it does the job
could you, please, change the comment so it's more helpful to the future readers? Like, "needed to show the tooltip when Mol* is in full screen mode but not when it's collapsed" or similar

2023-04-18 00:03 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/AlignmentTrajectoryPresetProvider.ts
> +            pdb: PD.Value<{entryId: string;entityId: string;}|{entryId: string;instanceId: string;}|undefined>(undefined),
why not make it required?

2023-04-18 23:29 UTC, bioinsilico commented on package.json
> +    "webpack-dev-server": "^4.11.1"
Yeah, old way never worked for me. I have uninstalled concurrently and http-server. I am not sure if there are more dependencies for the old testing.

2023-04-18 23:29 UTC, bioinsilico commented on src/saguaro-3d/ExternalAlignmentProvider.ts
> +    async getTargets(): Promise<string[]> {
bye bye annoying promises

2023-04-18 23:30 UTC, bioinsilico commented on src/saguaro-3d/AlignmentTrackFactory.ts
> +import { RcsbFvDisplayTypes, RcsbFvRowConfigInterface } from '@rcsb/rcsb-saguaro';
For reason rcsb-saguaro was not a dep

2023-04-18 23:31 UTC, bioinsilico commented on src/saguaro-3d/molstar-trajectory/AlignmentRepresentationPresetProvider.ts
> +import { TagDelimiter } from '@rcsb/rcsb-saguaro-app';
Good point. I will move this to rcsb-api-tools

2023-04-18 23:35 UTC, bioinsilico commented on src/saguaro-3d/molstar-trajectory/AlignmentTrajectoryPresetProvider.ts
> +                colorConfig.setAlignmentIdToModel(structure.data?.model.id, alignmentId);
ColorTheme was already unique. I think the code is a bit more difficult to read now, there is some kind of black magic how colors are propagated, but I guess now it follows molstar philosophy

2023-04-18 23:35 UTC, bioinsilico commented on src/saguaro-3d/molstar-trajectory/AlignmentRepresentationPresetProvider.ts
> +
Don't look at rcsb-molstar. I have refactored the code to make it more readable

2023-04-18 23:37 UTC, bioinsilico commented on src/saguaro-3d/molstar-trajectory/Coloring.ts
> +            const closeResidues = colorConfig.getCloseResidues(modelId);
IMO molstar black magic makes code more difficult to read. Done!

2023-04-18 23:38 UTC, bioinsilico commented on src/ui/plugin.tsx
>      useObservable<Status>(props.ctx.state.events.status, setState);
I moved the react prop update logic into structure component

2023-04-18 23:47 UTC, bioinsilico commented
Size won't be a problem since all modules are imported as libraries and never the final bundle. About the multiple version it can be a problem. A lot of bad experiences with multiple Reacts or rxjs ... I don't think is a good idea to re-export thinks the npm way is using peerDependencies and define what versions should be "injected" in the dependency. I have not used this feature yet, but is something that we need. For noe, I woul keep version consistent among the projects.

2023-04-20 06:59 UTC, valasatava commented on src/saguaro-3d/molstar-trajectory/Coloring.ts
> +    label: 'Close Residue Color',
Could we use "Equivalent Residues" as a label? This is how we call it in the summary table/Documentation

2023-04-21 17:56 UTC, valasatava commented
> Size won't be a problem since all modules are imported as libraries and never the final bundle. About the multiple version it can be a problem. A lot of bad experiences with multiple Reacts or rxjs ... I don't think is a good idea to re-export thinks the npm way is using peerDependencies and define what versions should be "injected" in the dependency. I have not used this feature yet, but is something that we need. For noe, I woul keep version consistent among the projects.

I like what you propose relating using peerDependencies, we should definitely explore this later

2023-04-21 17:56 UTC, valasatava approved these changes
Thank you for all adjustments!

2023-04-25 21:20 UTC, merged